// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEh1cQHmUDi7NkrAV0fZ9b7Oa-K17B6lo',
    appId: '1:325302199646:web:f44e6f206b2c7d2de41bcf',
    messagingSenderId: '325302199646',
    projectId: 'absensi-nanang',
    authDomain: 'absensi-nanang.firebaseapp.com',
    storageBucket: 'absensi-nanang.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc4c4ruX_aR38v2faa841FsRQJU8WfDoo',
    appId: '1:325302199646:android:4138aa1d46bc8dbde41bcf',
    messagingSenderId: '325302199646',
    projectId: 'absensi-nanang',
    storageBucket: 'absensi-nanang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwOwdHOMP_a8EjNrOU6-byBdOMYEKjMFw',
    appId: '1:325302199646:ios:b43ce7b6bc47341fe41bcf',
    messagingSenderId: '325302199646',
    projectId: 'absensi-nanang',
    storageBucket: 'absensi-nanang.appspot.com',
    iosClientId: '325302199646-rl02qa4hlhci3grnm4sdi8vtksj1ptmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensiNanang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwOwdHOMP_a8EjNrOU6-byBdOMYEKjMFw',
    appId: '1:325302199646:ios:6ecfde8ab42a687be41bcf',
    messagingSenderId: '325302199646',
    projectId: 'absensi-nanang',
    storageBucket: 'absensi-nanang.appspot.com',
    iosClientId: '325302199646-l9t5cbc65t0opqkhf5ouctg4h5p4gfou.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensiNanang.RunnerTests',
  );
}
